export default function handler(req, res) {
    res.status(200).json({
        agility: {picture: "/skill/agility.png"},
        attack: {picture: "/skill/attack.png"},
        defence: {picture: "/skill/defence.png"},
        hitpoints: {picture: "/skill/hitpoints.png"},
        prayer: {picture: "/skill/prayer.png"},
        ranged: {picture: "/skill/ranged.png"},
        runecraft: {picture: "/skill/runecraft.png"},
        slayer: {picture: "/skill/slayer.png"},
        strength: {picture: "/skill/strength.png"},
        thieving: {picture: "/skill/thieving.png"},
        woodcutting: {picture: "/skill/woodcutting.png"},
        construction: {picture: "/skill/construction.png"},
        hunter: {picture: "/skill/hunter.png"},
        mining: {picture: "/skill/mining.png"},
        smithing: {picture: "/skill/smithing.png"},
        fishing: {picture: "/skill/fishing.png"},
        cooking: {picture: "/skill/cooking.png"},
        firemaking: {picture: "/skill/firemaking.png"},
        farming: {picture: "/skill/farming.png"},
        crafting: {picture: "/skill/crafting.png"},
        magic: {picture: "/skill/magic.png"},
        fletching: {picture: "/skill/fletching.png"},
        total: {picture: "/skill/total.png"},
        herblore: {picture: "/skill/herblore.png"},  
    })
}